### PR TITLE
submitting the test

### PR DESCRIPTION
**Pull request by sumant14**
test done , creating pull request

### CODE REVIEW

**Comment by keshavram-apptware** [comment]
The resolved tests have been deprecated. Please refer to the new ones.

**Comment by sumant14** [comment]
Hi,

Can you pls let me know where can I find the new one test.




*Sumant Kumar*
------------------------------------------------------------------
*Contact No.:-** +91-955789679*
*E-Mail*:*- ***@***.*** ***@***.***>*
------------------------------------------------------------------

**Comment by sumant14** [comment]
Hi Keshavram,

Can you pls confirm which test should I refer as you have mentioned the
test is deprecated .

I can see one 5 days ago commit is that the new changes, pls confirm me in
the attached image




*Sumant Kumar*
------------------------------------------------------------------
*Contact No.:-** +91-955789679*
*E-Mail*:*- ***@***.*** ***@***.***>*
------------------------------------------------------------------

**Comment by keshavram-apptware** [comment]
@sumant14 The latest tests can be found in the `main` branch. We have introduced the Spring Beans Test

**Comment by sumant14** [comment]
Ok sure, I get it now, thank you, will update once completed.


*Sumant Kumar*
------------------------------------------------------------------
*Contact No.:-** +91-955789679*
*E-Mail*:*- ***@***.*** ***@***.***>*
------------------------------------------------------------------

**Pull request closed without merging**
